INSERT INTO public.account (account_firstname, account_lastname, account_email, account_password) VALUES
('Tony', 'Stark', 'tony@stark.com', 'IamIronM@n');

UPDATE public.account 
set  account_type = 'admin' 
where account_email = 'tony@stark.com';

DELETE FROM public.account 
WHERE account_email = 'tony@stark.com';

UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GMC' AND inv_model = 'Hummer';

SELECT inv_make, inv_model FROM public.inventory AS inv
INNER JOIN classification  AS 
clas ON inv.classification_id = clas.classification_id
WHERE clas.classification_name = 'Sport';

UPDATE public.inventory
SET inv_image = REPLACE(inv_image, ' /images', '/images/vehicles'),
    inv_thumbnail = REPLACE(inv_thumbnail, ' /images', '/images/vehicles')


create table support_ticket(
ticket_id int generated by default as identity,
account_id   INTEGER NOT NULL,
  subject      VARCHAR(150) NOT NULL,
  description  TEXT NOT NULL,

  date         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  status       VARCHAR(20) NOT NULL DEFAULT 'open'
               CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),

  CONSTRAINT fk_support_ticket_account
    FOREIGN KEY (account_id)
    REFERENCES account(account_id)
    ON DELETE CASCADE
);